# Generated by Django 6.0.9 on 2026-10-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SipiactTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.CharField(db_index=True, max_length=120)),
                ('uf', models.CharField(db_index=True, max_length=2)),
                ('ano', models.IntegerField(db_index=True)),
                ('total', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Total SIPIA-CT',
                'verbose_name_plural': 'Totais SIPIA-CT',
                'indexes': [models.Index(fields=['indicador', 'ano'], name='mapas_sipia_indicad_4a54fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('indicador', 'uf', 'ano'), name='uniq_sipiact_indicador_uf_ano')],
            },
        ),
    ]
