# Generated by Django 6.0.6 on 2026-06-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table', models.CharField(db_index=True, help_text='Tabela de origem: VIOLBR20..VIOLBR24', max_length=10)),
                ('data_notificacao', models.DateField(db_index=True)),
                ('data_ocorrencia', models.DateField(blank=True, null=True)),
                ('ano', models.PositiveSmallIntegerField(db_index=True)),
                ('semana_epi', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Ignorado')], db_index=True, max_length=1)),
                ('idade_anos', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Idade em anos. Bebês <1 ano = 0.', null=True)),
                ('faixa_etaria', models.CharField(db_index=True, help_text='< 1 ano | 1-4 | 5-9 | 10-14 | 15-19 | 20-59 | 60+ | Ignorada', max_length=12)),
                ('raca_cor', models.CharField(blank=True, db_index=True, help_text='Branca/Preta/Amarela/Parda/Indigena/Ignorada', max_length=12)),
                ('escolaridade', models.CharField(blank=True, max_length=60)),
                ('gestante', models.CharField(blank=True, max_length=40)),
                ('uf', models.CharField(blank=True, db_index=True, help_text='Sigla da UF de residencia (ex: SP, SE)', max_length=2)),
                ('uf_ocorrencia', models.CharField(blank=True, db_index=True, max_length=2)),
                ('municipio_codigo', models.CharField(blank=True, db_index=True, help_text='Codigo IBGE do municipio de residencia', max_length=7)),
                ('local_ocorrencia', models.CharField(blank=True, help_text='Residencia / Via publica / Escola / ...', max_length=60)),
                ('zona', models.CharField(blank=True, max_length=15)),
                ('violencia_fisica', models.BooleanField(db_index=True, null=True)),
                ('violencia_psicologica', models.BooleanField(db_index=True, null=True)),
                ('violencia_sexual', models.BooleanField(db_index=True, null=True)),
                ('tortura', models.BooleanField(db_index=True, null=True)),
                ('trafico_pessoas', models.BooleanField(db_index=True, null=True)),
                ('violencia_financeira', models.BooleanField(null=True)),
                ('negligencia', models.BooleanField(db_index=True, null=True)),
                ('violencia_infantil', models.BooleanField(db_index=True, null=True)),
                ('intervencao_legal', models.BooleanField(null=True)),
                ('outras_violencias', models.BooleanField(null=True)),
                ('lesao_autoprovocada', models.BooleanField(db_index=True, help_text='Auto-mutilacao ou tentativa de suicidio', null=True)),
                ('ocorreu_outras_vezes', models.BooleanField(help_text='Vitima reincidente', null=True)),
                ('autor_sexo', models.CharField(blank=True, help_text='M / F / I (sexo do autor)', max_length=1)),
                ('autor_alcool', models.CharField(blank=True, help_text='Sim / Nao / Ignorado', max_length=12)),
            ],
            options={
                'verbose_name': 'Notificação SINAM',
                'verbose_name_plural': 'Notificações SINAM',
                'ordering': ['-data_notificacao'],
                'indexes': [models.Index(fields=['uf', 'ano'], name='sinam_notif_uf_049da0_idx'), models.Index(fields=['ano', 'violencia_sexual'], name='sinam_notif_ano_faa7da_idx'), models.Index(fields=['ano', 'violencia_fisica'], name='sinam_notif_ano_f66bd4_idx')],
            },
        ),
    ]
