# Generated by Django 6.0.6 on 2026-06-05 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoDBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('source_table', models.CharField(db_index=True, help_text='Ex: VIOLBR25', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('decompressing', 'Descomprimindo .dbc'), ('inserting', 'Inserindo no banco'), ('done', 'Concluída'), ('error', 'Erro')], db_index=True, default='pending', max_length=20)),
                ('stage_detail', models.TextField(blank=True, help_text='Última mensagem de progresso.')),
                ('rows_inserted', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('rows_removed', models.PositiveIntegerField(default=0, help_text='Linhas anteriores apagadas (replace).')),
                ('decompress_seconds', models.FloatField(blank=True, null=True)),
                ('insert_seconds', models.FloatField(blank=True, null=True)),
                ('total_seconds', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_sinam', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importação SINAM',
                'verbose_name_plural': 'Importações SINAM',
                'ordering': ['-created_at'],
            },
        ),
    ]
