# Generated by Django 6.0.6 on 2026-06-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinam', '0002_importacaodbc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo', models.CharField(help_text='Código IBGE de 7 dígitos.', max_length=7, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('nome_normalizado', models.CharField(db_index=True, help_text='Lowercase, sem acentos — para busca fuzzy.', max_length=100)),
                ('uf', models.CharField(db_index=True, max_length=2)),
            ],
            options={
                'verbose_name': 'Município (IBGE)',
                'verbose_name_plural': 'Municípios (IBGE)',
                'ordering': ['uf', 'nome'],
            },
        ),
    ]
