# Generated by Django 6.0.6 on 2026-06-16 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('forecaster', models.CharField(default='chronos2', help_text='Forecaster backend key (chronos2, chattime, ...).', max_length=32)),
                ('model', models.CharField(default='qwen3:8b', help_text='Ollama model name used as orchestrator.', max_length=64)),
                ('temperature', models.FloatField(default=0.2, help_text='Temperatura de amostragem do orquestrador (0.0 = determinístico, 1.0 = criativo). 0.2 dá respostas estáveis e baixa alucinação.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'system'), ('user', 'user'), ('assistant', 'assistant'), ('tool', 'tool')], max_length=16)),
                ('content', models.TextField(blank=True)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('tool_name', models.CharField(blank=True, max_length=64)),
                ('tool_payload', models.JSONField(blank=True, default=dict)),
                ('elapsed_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orquestrador.chatthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
