# Generated by Django 6.0.6 on 2026-10-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquestrador', '0004_chatmessage_forecaster_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='model',
            field=models.CharField(default='jurema-7b', help_text='Ollama model name used as the answer generator (Aurora Responde: Jurema-7B).', max_length=64),
        ),
    ]
